import { Example } from "./App";

export const data: Example[] = [
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
];
