import { Example } from "./App";
import { ColumnDef } from "@tanstack/react-table";
import { HeaderOptionType } from "./type/type";

export const columns: ColumnDef<Example>[] = [
  {
    accessorKey: "No",
    header: "No",
    enableSorting: true,
  },
  { accessorKey: "firstName", header: "First Name", enableSorting: false },
  {
    accessorKey: "lastName",
    header: "Last Name",
    enableSorting: false,
  },
  // {
  //   header: "information", // 큰 헤더
  //   columns: [
  //     {
  //       accessorKey: "height",
  //       header: "height", // 서브 헤더
  //     },

  //     {
  //       header: "weight", // 서브 헤더
  //       columns: [
  //         { accessorKey: "10kg", header: "10kg" },
  //         { accessorKey: "20kg", header: "20kg" },
  //       ],
  //     },
  //   ],
  // },
];

export const headerOptionType: HeaderOptionType[] = [
  { accessorKey: "No", layer: 1, rowSpan: 3, colSpan: 1 },
  { accessorKey: "firstName", layer: 1, rowSpan: 3, colSpan: 1 },
  {
    accessorKey: "lastName",
    layer: 1,
    rowSpan: 3,
    colSpan: 1,
  },
  {
    accessorKey: "information",
    layer: 1,
    rowSpan: 1,
    colSpan: 3,
  },
  {
    accessorKey: "weight",
    layer: 2,
    rowSpan: 1,
    colSpan: 2,
  },
  {
    accessorKey: "height",
    layer: 2,
    rowSpan: 2,
    colSpan: 1,
  },
];

const originData: Example[] = [
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "Jane",
    lastName: "Doe",
    height: 26,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
  {
    No: 1,
    firstName: "John",
    lastName: "Doe",
    height: 28,
    weight: 50,
    "10kg": "yes",
    "20kg": "no",
  },
];

// 🔵 custom for test 🔵
export const data = originData.map((data, index) => {
  data.No = index + 1;
  return data;
});
